# yamllint disable rule:line-length
---
name: run snyk-cli:docker scan

description: use snyk to scan docker image for vulnerabilities

inputs:

  working-directory:
    description: set working directory. Default is ./.
    required: false
    default: "."

  registry:
    description: dtr compatible registry
    required: false
    default: docker.io

  organization:
    description: dtr compatible organization identified
    required: false
    default: ""

  path:
    description: path to the directory containing your Dockerfile and build context
    required: false
    default: .

  image:
    description: name of image
    required: true

  tag:
    description: value for tag
    required: false
    default: dev.${GITHUB_SHA:0:7}

  dockerfile:
    description: name of dockerfile
    required: false
    default: "Dockerfile"

  snyk-severity-threshold:
    description: snyk test reporting threshold
    required: false
    default: low

  snyk-token:
    description: snyk api-token
    required: false
    default: SNYK_TOKEN

  snyk-organization:
    description: Name of snyk organization
    required: true

  snyk-skip-base-image:
    description: optionally, skip performing cve scan of base image
    required: false
    default: "false"

  snyk-additional-args:
    description: additional custom command line flags
    required: false
    default: ""

  security-scan-nofail:
    description: >
      security scan revealing issues will not cause pipeline to fail,
      instead the scan output will be uploaded as a pipeline artifact
    required: false
    default: "false"

runs:
  using: "composite"

  steps:
    - name: snyk cli image scan
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -eo pipefail
        outfilename="${{ inputs.image }}_${{ inputs.tag }}_snyk_scan.log"
        echo "outfilename=$outfilename" >> $GITHUB_ENV


        if [[ ! ${{ inputs.snyk-skip-base-image }} ]]; then
          skip_base_image=""
        else
          skip_base_image="--exclude-base-image-vulns"
        fi
        snyk config set api=${{ inputs.snyk-token }}
        snyk config set org=${{ inputs.snyk-organization }}
        snyk test ${{ inputs.snyk-additional-args }} \
                  $skip_base_image \
                  --docker ${{ inputs.registry }}/${{ inputs.organization }}/${{ inputs.image }}:${{ inputs.tag }} \
                  -file=${{ inputs.path }}/${{ inputs.dockerfile }} \
                  --policy-path=./.snyk \
                  --severity-threshold=${{ inputs.snyk-severity-threshold }} 2>&1 | tee $outfilename
        if [[ "${{ inputs.security-scan-nofail }}" == "true" ]]; then
          exit 0
        fi

    - name: upload snyk scan log as saved artifact
      if: ${{ inputs.security-scan-nofail == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.outfilename }}
        path: ${{ env.outfilename }}
        retention-days: 7
