# yamllint disable rule:line-length
# yamllint disable rule:truthy
---
name: action static code analysis workflow

on:
  workflow_call:

    secrets:
      OP_SERVICE_ACCOUNT_TOKEN:
        description: 1password vault services account token
        required: false

    inputs:

      working-directory:
        description: set working directory, Default is ./.
        required: false
        type: string
        default: .

      shellcheck-version:
        description: set shellcheck version
        required: false
        type: string
        default: v0.10.0

      shellcheck-exclude:
        description: list of checks to exclude; -e SC2059 -e SC2034 -e SC1090
        required: false
        type: string
        default: ""

      shellcheck-ignore-paths:
        description: paths to ignore
        required: false
        type: string
        default: ""

      shellcheck-ignore-names:
        description: specific files to ignore
        required: false
        type: string
        default: ""

      shellcheck-severity:
        description: severity level; error, warn, info, style (default)
        required: false
        type: string
        default: "style"

      shellcheck-check-together:
        description: check all files together
        required: false
        type: string
        default: "no"

      shellcheck-scandir:
        description: directory to scan
        required: false
        type: string
        default: "."

      shellcheck-additional-files:
        description: check for unusual files
        required: false
        type: string
        default: ""

      shellcheck-format:
        description: output format; tty (default), gcc, checkstyle, diff, json1, json, quiet
        required: false
        type: string
        default: "gcc"

      before-static-analysis:
        description: optionally call ./.github/actions/before-static-analysis before static analysis
        required: false
        type: string
        default: "false"

      after-static-analysis:
        description: optionally call ./.github/actions/after-static-analysis after static analysis
        required: false
        type: string
        default: "false"

permissions:
  contents: read
  security-events: write

jobs:

  static-code-analysis:
    name: gha-tools-action static code analysis workflow
    runs-on: ubuntu-latest

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332      # v4.1.7

      - name: run custom before-static-analysis action
        if: ${{ inputs.before-static-analysis != 'false' }}
        uses: ./.github/actions/before-static-analysis
        with:
          instance: ${{ inputs.before-static-analysis }}

      - name: gha-tools-action/lint
        uses: twplatformlabs/gha-tools-action/lint@main

      - name: gha-tools-action/check
        uses: twplatformlabs/gha-tools-action/check@main
        with:
          working-directory: ${{ inputs.working-directory }}
          shellcheck-version: ${{ inputs.shellcheck-version }}
          shellcheck-exclude: ${{ inputs.shellcheck-exclude }}
          shellcheck-ignore-paths: ${{ inputs.shellcheck-ignore-paths }}
          shellcheck-ignore-names: ${{ inputs.shellcheck-ignore-names }}
          shellcheck-severity: ${{ inputs.shellcheck-severity }}
          shellcheck-check-together: ${{ inputs.shellcheck-check-together }}
          shellcheck-scandir: ${{ inputs.shellcheck-scandir }}
          shellcheck-additional-files: ${{ inputs.shellcheck-additional-files }}
          shellcheck-format: ${{ inputs.shellcheck-format }}

      - name: gha-tools-action/scorecard
        uses: twplatformlabs/gha-tools-action/scorecard@main

      - name: run custom after-static-analysis action
        if: ${{ inputs.after-static-analysis != 'false' }}
        uses: ./.github/actions/after-static-analysis
        with:
          instance: ${{ inputs.after-static-analysis }}
